name: Container Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup variables
        run: |
          export IMAGE=pytorch-datastream
          echo "::set-env name=IMAGE::$IMAGE" # HACK export env between github action steps
          export RTAG=r${GITHUB_RUN_NUMBER}
          echo "::set-env name=RTAG::$RTAG" # HACK export env between github action steps
          export SHATAG=s${GITHUB_SHA}
          echo "::set-env name=SHATAG::$SHATAG" # HACK export env between github action steps

      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build . \
            --tag ${IMAGE}:${SHATAG}

      - name: Test
        run: |
          docker run \
            --interactive \
            ${IMAGE}:${SHATAG} \
            -c pytest
