name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python - --version 1.2.2
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests
        run: |
          poetry run pytest

      - name: Build wheels
        run: |
          poetry version $(git tag --points-at HEAD)
          poetry build

      - name: Test install package
        run: |
          mkdir test_install
          cd test_install
          poetry init
          poetry add ../dist/$(ls dist/*.whl)

          poetry run python -c "import datastream"

      - name: Upload
        env:
          USERNAME: __token__
          PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username=$USERNAME --password=$PASSWORD
